//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataViewer.Models
{

    public partial class GE_GeologicEvent
    {
        public int GE_ID { get; set; }
        public int GF_ID { get; set; }
        public string YoungerAge { get; set; }
        public string OlderAge { get; set; }
        public string EventProcess { get; set; }
        public string EventEnvironment { get; set; }
        public string Notes { get; set; }
        public string MainAge { get; set; }
    
        public virtual GE_GeologicFeature GE_GeologicFeature { get; set; }
    }
}
