//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataViewer.Models
{
    using System.Collections.Generic;

    public partial class GE_GeologicUnit
    {
        public GE_GeologicUnit()
        {
            this.GE_CompositionPart = new HashSet<GE_CompositionPart>();
        }
    
        public int GU_ID { get; set; }
        public int GF_ID { get; set; }
        public string GeologicUnitType { get; set; }
        public string GeologicUnitName { get; set; }
        public string TectonicUnit { get; set; }
        public bool CompoundUnit { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<GE_CompositionPart> GE_CompositionPart { get; set; }
        public virtual GE_GeologicFeature GE_GeologicFeature { get; set; }
    }
}
