//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataViewer.Models
{
    using System;

    public partial class THESAURUS_concept
    {
        public string URI { get; set; }
        public string ThesaurusURI { get; set; }
        public string PrefLabelDe { get; set; }
        public string PrefLabelEn { get; set; }
        public string DescriptionDe { get; set; }
        public string DescriptionEn { get; set; }
        public string HexColor { get; set; }
        public string GbaStatus { get; set; }
        public Nullable<double> PosLong { get; set; }
        public Nullable<double> PosLat { get; set; }
        public string BroaderConceptURI { get; set; }
        public string BroaderConceptPrefLabelDe { get; set; }
        public string BroaderConceptPrefLabelEn { get; set; }
        public string ConceptSchemeURI { get; set; }
        public string ConceptSchemeTitleDe { get; set; }
        public string ConceptSchemeTitleEn { get; set; }
        public string TopConceptURI { get; set; }
        public string TopConceptPrefLabelDe { get; set; }
        public string TopConceptPrefLabelEn { get; set; }
        public string InspireMappingURI { get; set; }
        public string DBpediaMappingURI { get; set; }
        public string GeoscimlMappingURI { get; set; }
        public string BgsMappingURI { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string E_USER { get; set; }
        public Nullable<System.DateTime> E_DATUM { get; set; }
        public string A_USER { get; set; }
        public Nullable<System.DateTime> A_DATUM { get; set; }
        public string Notation { get; set; }
    }
}
