//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataViewer.Models
{
    using System;

    public partial class THESAURUS_geosciml
    {
        public string URI { get; set; }
        public string prefLabel_EN { get; set; }
        public string definition_EN { get; set; }
        public string source_EN { get; set; }
        public string exactMatch_URI { get; set; }
        public string inScheme_URI { get; set; }
        public Nullable<System.DateTime> DateExported { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool active { get; set; }
    }
}
