//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataViewer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThesaurusContext : DbContext
    {
        public ThesaurusContext()
            : base("name=ThesaurusContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GE_CompositionPart> GE_CompositionPart { get; set; }
        public virtual DbSet<GE_GeologicEvent> GE_GeologicEvent { get; set; }
        public virtual DbSet<GE_GeologicFeature> GE_GeologicFeature { get; set; }
        public virtual DbSet<GE_GeologicUnit> GE_GeologicUnit { get; set; }
        public virtual DbSet<THESAURUS_geosciml> THESAURUS_geosciml { get; set; }
        public virtual DbSet<THESAURUS_concept> THESAURUS_concept { get; set; }
    }
}
